-- =============================================================================
-- 02_raw_tables.sql
-- IoT Predictive Maintenance Platform - RAW Schema Table Definitions
-- =============================================================================

USE DATABASE IOT_PREDICTIVE_MAINTENANCE;
USE SCHEMA RAW;

-- ---- OT / Sensor Data ----

CREATE OR REPLACE TABLE MACHINES (
    MACHINE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    MACHINE_NAME VARCHAR(100),
    MACHINE_TYPE VARCHAR(50),
    MANUFACTURER VARCHAR(100),
    MODEL_NUMBER VARCHAR(50),
    LOCATION VARCHAR(100),
    INSTALL_DATE DATE,
    LAST_OVERHAUL_DATE DATE,
    RATED_POWER_KW FLOAT,
    RATED_CURRENT_A FLOAT,
    RATED_RPM NUMBER(38,0),
    MAX_VIBRATION_MM_S FLOAT,
    MAX_BEARING_TEMP_C FLOAT,
    MAX_HYDRAULIC_PRESSURE_BAR FLOAT,
    STATUS VARCHAR(20) DEFAULT 'OPERATIONAL',
    CRITICALITY VARCHAR(10),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SENSORS (
    SENSOR_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20) REFERENCES MACHINES(MACHINE_ID),
    SENSOR_TYPE VARCHAR(30),
    SENSOR_NAME VARCHAR(100),
    UNIT VARCHAR(20),
    MIN_THRESHOLD FLOAT,
    MAX_THRESHOLD FLOAT,
    INSTALL_DATE DATE,
    CALIBRATION_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SENSOR_READINGS (
    READING_ID VARCHAR(36),
    SENSOR_ID VARCHAR(20),
    MACHINE_ID VARCHAR(20),
    READING_TIMESTAMP TIMESTAMP_NTZ,
    SENSOR_TYPE VARCHAR(30),
    VALUE FLOAT,
    UNIT VARCHAR(20),
    QUALITY_FLAG VARCHAR(10) DEFAULT 'GOOD',
    IS_ANOMALY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MACHINE_EVENT_LOGS (
    EVENT_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    EVENT_TYPE VARCHAR(30),
    EVENT_CODE VARCHAR(20),
    SEVERITY VARCHAR(10),
    DESCRIPTION VARCHAR(500),
    SEQUENCE_NUMBER NUMBER(38,0),
    ROOT_CAUSE_GROUP VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE POWER_QUALITY_LOGS (
    LOG_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    LOG_TIMESTAMP TIMESTAMP_NTZ,
    VOLTAGE_V FLOAT,
    FREQUENCY_HZ FLOAT,
    POWER_FACTOR FLOAT,
    EVENT_TYPE VARCHAR(30),
    DURATION_MS NUMBER(38,0),
    SEVERITY VARCHAR(10),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---- ERP / Historical Data ----

CREATE OR REPLACE TABLE MAINTENANCE_HISTORY (
    RECORD_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    FAILURE_DATE DATE,
    FAILURE_TYPE VARCHAR(50),
    ROOT_CAUSE VARCHAR(200),
    RESOLUTION VARCHAR(500),
    PARTS_REPLACED VARCHAR(500),
    DOWNTIME_HOURS FLOAT,
    COST_USD FLOAT,
    TECHNICIAN_ID VARCHAR(20),
    TECHNICIAN_NOTES VARCHAR(1000),
    TROUBLESHOOT_METHOD VARCHAR(200),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PARTS_INVENTORY (
    PART_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    PART_NAME VARCHAR(100),
    PART_CATEGORY VARCHAR(50),
    COMPATIBLE_MACHINE_TYPES VARIANT,
    QUANTITY_IN_STOCK NUMBER(38,0),
    REORDER_LEVEL NUMBER(38,0),
    LEAD_TIME_DAYS NUMBER(38,0),
    UNIT_COST_USD FLOAT,
    LAST_REPLACED_MACHINE_ID VARCHAR(20),
    LAST_REPLACED_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TOOLING_CHANGES (
    CHANGE_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    CHANGE_DATE DATE,
    OLD_TOOL VARCHAR(100),
    NEW_TOOL VARCHAR(100),
    REASON VARCHAR(200),
    LOAD_IMPACT_PERCENT FLOAT,
    CHANGED_BY VARCHAR(50),
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PRODUCTION_QUALITY (
    RECORD_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    SHIFT_DATE DATE,
    SHIFT_NUMBER NUMBER(38,0),
    PARTS_PRODUCED NUMBER(38,0),
    PARTS_REJECTED NUMBER(38,0),
    AVG_CYCLE_TIME_SEC FLOAT,
    PREV_SHIFT_CYCLE_TIME_SEC FLOAT,
    TOLERANCE_DEVIATION_MM FLOAT,
    SURFACE_FINISH_RA FLOAT,
    VOLUME_VS_TARGET_PCT FLOAT,
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---- Human Context ----

CREATE OR REPLACE TABLE SHIFT_LOGS (
    LOG_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    OPERATOR_ID VARCHAR(20),
    SHIFT_DATE DATE,
    SHIFT_NUMBER NUMBER(38,0),
    LOG_TIMESTAMP TIMESTAMP_NTZ,
    OBSERVATION_TYPE VARCHAR(30),
    DESCRIPTION VARCHAR(1000),
    SEVERITY VARCHAR(10),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TECHNICIAN_DIAGNOSTICS (
    DIAG_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    WORK_ORDER_ID VARCHAR(36),
    MACHINE_ID VARCHAR(20),
    TECHNICIAN_ID VARCHAR(20),
    DIAG_TIMESTAMP TIMESTAMP_NTZ,
    HYPOTHESIS VARCHAR(500),
    INSPECTION_TYPE VARCHAR(30),
    FINDINGS VARCHAR(1000),
    SIMILAR_PAST_INCIDENT VARCHAR(36),
    PARTS_TESTED VARIANT,
    RESULT VARCHAR(20),
    NEXT_STEP VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE WORK_ORDERS (
    WORK_ORDER_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    MACHINE_ID VARCHAR(20),
    ANOMALY_ID VARCHAR(36),
    STATUS VARCHAR(20) DEFAULT 'DRAFT',
    PRIORITY VARCHAR(10),
    TITLE VARCHAR(200),
    PROBLEM_DESCRIPTION VARCHAR(2000),
    RECOMMENDED_ACTIONS VARCHAR(2000),
    ASSIGNED_TECHNICIAN_ID VARCHAR(20),
    ESTIMATED_DOWNTIME_HOURS FLOAT,
    ACTUAL_DOWNTIME_HOURS FLOAT,
    PARTS_NEEDED VARIANT,
    RENTAL_RECOMMENDED BOOLEAN DEFAULT FALSE,
    RENTAL_MACHINE_ID VARCHAR(20),
    RENTAL_COST_USD FLOAT,
    CROSS_MACHINE_CHECK VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ,
    RESOLVED_AT TIMESTAMP_NTZ
);

-- ---- Business Continuity ----

CREATE OR REPLACE TABLE RENTAL_MACHINES (
    RENTAL_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    MACHINE_TYPE VARCHAR(50),
    VENDOR VARCHAR(100),
    DAILY_COST_USD FLOAT,
    WEEKLY_COST_USD FLOAT,
    AVAILABILITY VARCHAR(20),
    LEAD_TIME_DAYS NUMBER(38,0),
    CAPACITY_PERCENT FLOAT,
    LOCATION VARCHAR(100),
    CONTACT_INFO VARCHAR(200),
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---- Analytics Output Tables ----

CREATE OR REPLACE TABLE IOT_PREDICTIVE_MAINTENANCE.ANALYTICS.DETECTED_ANOMALIES (
    ANOMALY_ID TEXT NOT NULL,
    MACHINE_ID TEXT,
    MACHINE_TYPE TEXT,
    DETECTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    READING_TIMESTAMP TIMESTAMP_NTZ,
    SENSOR_TYPE TEXT,
    SENSOR_VALUE FLOAT,
    IS_ANOMALY BOOLEAN,
    ANOMALY_SCORE FLOAT,
    SEVERITY TEXT,
    SEVERITY_REASONING TEXT,
    FORECAST_7D FLOAT,
    FORECAST_14D FLOAT,
    HEALTH_SCORE FLOAT,
    HEALTH_STATUS TEXT,
    OPERATOR_OBSERVATION TEXT,
    OPERATOR_NOTES TEXT,
    PERFORMANCE_STATUS TEXT,
    REJECT_RATE_PCT FLOAT,
    POWER_EVENT TEXT,
    LAST_FAILURE_TYPE TEXT,
    RECOMMENDED_ACTION TEXT,
    STATUS TEXT DEFAULT 'NEW',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE IOT_PREDICTIVE_MAINTENANCE.ANALYTICS.TRIAGE_QUEUE (
    TRIAGE_ID TEXT NOT NULL,
    ANOMALY_ID TEXT,
    MACHINE_ID TEXT,
    MACHINE_TYPE TEXT,
    READING_TIMESTAMP TIMESTAMP_NTZ,
    SEVERITY TEXT,
    SEVERITY_REASONING TEXT,
    SENSOR_VALUE FLOAT,
    ANOMALY_SCORE FLOAT,
    HEALTH_SCORE FLOAT,
    HEALTH_STATUS TEXT,
    FORECAST_7D FLOAT,
    FORECAST_14D FLOAT,
    OPERATOR_CONTEXT TEXT,
    PRODUCTION_CONTEXT TEXT,
    POWER_CONTEXT TEXT,
    MAINTENANCE_HISTORY_CONTEXT TEXT,
    CROSS_MACHINE_CONTEXT TEXT,
    PARTS_CONTEXT TEXT,
    RENTAL_CONTEXT TEXT,
    STATUS TEXT DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
