-- ============================================================
-- 02_raw_tables.sql
-- RAW schema table definitions (10 tables)
-- ============================================================

USE DATABASE IOT_PREDICTIVE_MAINTENANCE;
USE SCHEMA RAW;

-- 1. Machines
CREATE OR REPLACE TABLE MACHINES (
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    MACHINE_NAME        VARCHAR(100)  NOT NULL,
    MACHINE_TYPE        VARCHAR(50)   NOT NULL,
    LINE                VARCHAR(20)   NOT NULL,
    STATION             VARCHAR(20),
    LOCATION            VARCHAR(100),
    RATED_RPM           NUMBER(10,2),
    RATED_CURRENT       NUMBER(10,2),
    RATED_PRESSURE      NUMBER(10,2),
    CRITICALITY         VARCHAR(10)   NOT NULL,
    INSTALL_DATE        DATE,
    LAST_OVERHAUL_DATE  DATE,
    OPERATING_STATE     VARCHAR(20)   DEFAULT 'RUNNING',
    MANUFACTURER        VARCHAR(100),
    MODEL_NUMBER        VARCHAR(50),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_MACHINES PRIMARY KEY (MACHINE_ID)
);

-- 2. Sensors
CREATE OR REPLACE TABLE SENSORS (
    SENSOR_ID           VARCHAR(30)   NOT NULL,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    SIGNAL_TYPE         VARCHAR(30)   NOT NULL,
    UNIT                VARCHAR(20)   NOT NULL,
    MIN_THRESHOLD       NUMBER(12,4),
    MAX_THRESHOLD       NUMBER(12,4),
    WARNING_THRESHOLD   NUMBER(12,4),
    CRITICAL_THRESHOLD  NUMBER(12,4),
    SAMPLING_INTERVAL_SEC NUMBER(10)  DEFAULT 60,
    INSTALL_DATE        DATE,
    IS_ACTIVE           BOOLEAN       DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SENSORS PRIMARY KEY (SENSOR_ID),
    CONSTRAINT FK_SENSORS_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MACHINES(MACHINE_ID)
);

-- 3. Sensor Readings (high-volume time-series)
CREATE OR REPLACE TABLE SENSOR_READINGS (
    READING_ID          NUMBER AUTOINCREMENT,
    SENSOR_ID           VARCHAR(30)   NOT NULL,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    SIGNAL_TYPE         VARCHAR(30)   NOT NULL,
    READING_VALUE       NUMBER(14,4),
    READING_TIMESTAMP   TIMESTAMP_NTZ NOT NULL,
    QUALITY_FLAG        VARCHAR(10)   DEFAULT 'GOOD',
    SOURCE_SYSTEM       VARCHAR(30)   DEFAULT 'OT_GATEWAY',
    INGESTED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) CLUSTER BY (MACHINE_ID, READING_TIMESTAMP);

-- 4. Machine Event Logs
CREATE OR REPLACE TABLE MACHINE_EVENT_LOGS (
    EVENT_ID            NUMBER AUTOINCREMENT,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    EVENT_TYPE          VARCHAR(30)   NOT NULL,
    EVENT_CODE          VARCHAR(20),
    EVENT_DESCRIPTION   VARCHAR(500),
    SEVERITY            VARCHAR(10),
    EVENT_TIMESTAMP     TIMESTAMP_NTZ NOT NULL,
    RESOLVED_TIMESTAMP  TIMESTAMP_NTZ,
    OPERATOR_ID         VARCHAR(20),
    INGESTED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Maintenance History
CREATE OR REPLACE TABLE MAINTENANCE_HISTORY (
    MAINTENANCE_ID      VARCHAR(20)   NOT NULL,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    FAILURE_MODE        VARCHAR(100),
    ROOT_CAUSE          VARCHAR(500),
    ACTION_TAKEN        VARCHAR(500),
    PARTS_REPLACED      VARCHAR(500),
    REPAIR_DURATION_HRS NUMBER(8,2),
    DOWNTIME_HRS        NUMBER(8,2),
    COST                NUMBER(12,2),
    TECHNICIAN_ID       VARCHAR(20),
    MAINTENANCE_TYPE    VARCHAR(30),
    STARTED_AT          TIMESTAMP_NTZ,
    COMPLETED_AT        TIMESTAMP_NTZ,
    NOTES               VARCHAR(2000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_MAINTENANCE PRIMARY KEY (MAINTENANCE_ID)
);

-- 6. Parts Inventory
CREATE OR REPLACE TABLE PARTS_INVENTORY (
    PART_ID             VARCHAR(20)   NOT NULL,
    PART_NAME           VARCHAR(100)  NOT NULL,
    PART_CATEGORY       VARCHAR(50),
    COMPATIBLE_MACHINE_TYPES VARCHAR(200),
    COMPATIBLE_COMPONENTS VARCHAR(200),
    QUANTITY_ON_HAND    NUMBER(10)    DEFAULT 0,
    REORDER_POINT       NUMBER(10)    DEFAULT 5,
    LEAD_TIME_DAYS      NUMBER(5)     DEFAULT 7,
    UNIT_COST           NUMBER(10,2),
    SUPPLIER            VARCHAR(100),
    LAST_RESTOCKED_AT   TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PARTS PRIMARY KEY (PART_ID)
);

-- 7. Tooling Changes
CREATE OR REPLACE TABLE TOOLING_CHANGES (
    CHANGE_ID           NUMBER AUTOINCREMENT,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    TOOL_NAME           VARCHAR(100),
    CHANGE_REASON       VARCHAR(200),
    PREVIOUS_TOOL_LIFE_HRS NUMBER(10,2),
    NEW_TOOL_INSTALLED  BOOLEAN       DEFAULT TRUE,
    PRODUCTION_CONTEXT  VARCHAR(200),
    CHANGED_AT          TIMESTAMP_NTZ NOT NULL,
    OPERATOR_ID         VARCHAR(20),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8. Production Quality
CREATE OR REPLACE TABLE PRODUCTION_QUALITY (
    PRODUCTION_ID       NUMBER AUTOINCREMENT,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    SHIFT               VARCHAR(10)   NOT NULL,
    PRODUCTION_DATE     DATE          NOT NULL,
    PLANNED_UNITS       NUMBER(10),
    ACTUAL_UNITS        NUMBER(10),
    GOOD_UNITS          NUMBER(10),
    REJECTED_UNITS      NUMBER(10),
    CYCLE_TIME_SEC      NUMBER(10,2),
    IDEAL_CYCLE_TIME_SEC NUMBER(10,2),
    PLANNED_RUNTIME_HRS NUMBER(8,2),
    ACTUAL_RUNTIME_HRS  NUMBER(8,2),
    DOWNTIME_HRS        NUMBER(8,2)   DEFAULT 0,
    QUALITY_DEVIATION   NUMBER(8,4),
    PRODUCTION_STATUS   VARCHAR(20)   DEFAULT 'NORMAL',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 9. Shift Logs (Operator Observations)
CREATE OR REPLACE TABLE SHIFT_LOGS (
    LOG_ID              NUMBER AUTOINCREMENT,
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    OPERATOR_ID         VARCHAR(20)   NOT NULL,
    SHIFT               VARCHAR(10)   NOT NULL,
    OBSERVATION_TYPE    VARCHAR(30),
    OBSERVATION_DETAIL  VARCHAR(500),
    SEVERITY            VARCHAR(10),
    OBSERVED_AT         TIMESTAMP_NTZ NOT NULL,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 10. Work Orders
CREATE OR REPLACE TABLE WORK_ORDERS (
    WORK_ORDER_ID       VARCHAR(20)   NOT NULL,
    INCIDENT_ID         VARCHAR(20),
    MACHINE_ID          VARCHAR(20)   NOT NULL,
    STATUS              VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    PRIORITY            VARCHAR(10),
    PROBLEM_DESCRIPTION VARCHAR(2000),
    EVIDENCE_SUMMARY    VARCHAR(2000),
    PREDICTED_FAILURE_MODE VARCHAR(100),
    RECOMMENDED_ACTIONS VARCHAR(2000),
    REQUIRED_PARTS      VARCHAR(500),
    ESTIMATED_REPAIR_HRS NUMBER(8,2),
    ESTIMATED_DOWNTIME_HRS NUMBER(8,2),
    RECOMMENDED_WINDOW  VARCHAR(200),
    ASSIGNED_TECHNICIAN VARCHAR(20),
    APPROVED_BY         VARCHAR(20),
    APPROVED_AT         TIMESTAMP_NTZ,
    REJECTION_REASON    VARCHAR(500),
    ACTUAL_ROOT_CAUSE   VARCHAR(500),
    ACTUAL_PARTS_REPLACED VARCHAR(500),
    ACTUAL_REPAIR_HRS   NUMBER(8,2),
    TECHNICIAN_FINDINGS VARCHAR(2000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT         TIMESTAMP_NTZ,
    CONSTRAINT PK_WORK_ORDERS PRIMARY KEY (WORK_ORDER_ID)
);
