-- ============================================================
-- 04_dynamic_tables.sql
-- Feature Pipeline: 6 Dynamic Tables
-- Database: IOT_PREDICTIVE_MAINTENANCE | Warehouse: IOT_PM_WH
-- ============================================================

USE DATABASE IOT_PREDICTIVE_MAINTENANCE;
USE WAREHOUSE IOT_PM_WH;

-- ============================================================
-- DT1: STAGING.SENSOR_READINGS_CLEAN
-- Cleans raw readings, adds threshold flags, spike detection
-- ============================================================
CREATE OR REPLACE DYNAMIC TABLE STAGING.SENSOR_READINGS_CLEAN
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = IOT_PM_WH
    AS
SELECT
    sr.READING_ID,
    sr.SENSOR_ID,
    sr.MACHINE_ID,
    sr.SIGNAL_TYPE,
    sr.READING_TIMESTAMP,
    sr.READING_VALUE AS RAW_VALUE,
    CASE WHEN sr.READING_VALUE IS NULL THEN 'MISSING' ELSE sr.QUALITY_FLAG END AS QUALITY_FLAG,
    CASE
        WHEN sr.SIGNAL_TYPE = 'TEMPERATURE' AND s.UNIT = 'F'
            THEN ROUND((sr.READING_VALUE - 32) * 5.0/9.0, 2)
        ELSE sr.READING_VALUE
    END AS NORMALIZED_VALUE,
    CASE WHEN sr.READING_VALUE >= s.CRITICAL_THRESHOLD THEN 'CRITICAL'
         WHEN sr.READING_VALUE >= s.WARNING_THRESHOLD  THEN 'WARNING'
         ELSE 'NORMAL'
    END AS THRESHOLD_STATUS,
    CASE WHEN DATEDIFF('second', LAG(sr.READING_TIMESTAMP) OVER (
            PARTITION BY sr.SENSOR_ID ORDER BY sr.READING_TIMESTAMP
         ), sr.READING_TIMESTAMP) > s.SAMPLING_INTERVAL_SEC * 3
         THEN TRUE ELSE FALSE
    END AS IS_STALE,
    CASE WHEN ABS(sr.READING_VALUE - AVG(sr.READING_VALUE) OVER (
            PARTITION BY sr.SENSOR_ID ORDER BY sr.READING_TIMESTAMP
            ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING
         )) > 3 * STDDEV(sr.READING_VALUE) OVER (
            PARTITION BY sr.SENSOR_ID ORDER BY sr.READING_TIMESTAMP
            ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING
         )
         THEN TRUE ELSE FALSE
    END AS IS_SPIKE,
    s.WARNING_THRESHOLD,
    s.CRITICAL_THRESHOLD,
    s.UNIT
FROM RAW.SENSOR_READINGS sr
JOIN RAW.SENSORS s ON sr.SENSOR_ID = s.SENSOR_ID;

-- ============================================================
-- DT2: STAGING.MACHINE_OPERATING_CONTEXT
-- Derives current machine state, load context, suppression flags
-- ============================================================
CREATE OR REPLACE DYNAMIC TABLE STAGING.MACHINE_OPERATING_CONTEXT
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = IOT_PM_WH
    AS
WITH latest_events AS (
    SELECT MACHINE_ID, EVENT_TYPE, EVENT_CODE, EVENT_TIMESTAMP,
           ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY EVENT_TIMESTAMP DESC) AS rn
    FROM RAW.MACHINE_EVENT_LOGS
    WHERE EVENT_TYPE IN ('STARTUP','SHUTDOWN','STATE_CHANGE','FAULT')
),
machine_state AS (
    SELECT MACHINE_ID, EVENT_TYPE, EVENT_CODE, EVENT_TIMESTAMP
    FROM latest_events WHERE rn = 1
)
SELECT
    m.MACHINE_ID, m.MACHINE_NAME, m.MACHINE_TYPE, m.LINE, m.CRITICALITY,
    m.RATED_RPM, m.RATED_CURRENT,
    COALESCE(
        CASE WHEN ms.EVENT_TYPE = 'SHUTDOWN' THEN 'OFFLINE'
             WHEN ms.EVENT_TYPE = 'FAULT' THEN 'FAULT'
             WHEN ms.EVENT_CODE = 'SC-HIGHLOAD' THEN 'HIGH_LOAD'
             ELSE m.OPERATING_STATE END,
        m.OPERATING_STATE
    ) AS CURRENT_STATE,
    rpm.AVG_RPM,
    CASE WHEN m.RATED_RPM > 0 AND rpm.AVG_RPM IS NOT NULL
         THEN ROUND(rpm.AVG_RPM / m.RATED_RPM * 100, 1) ELSE NULL END AS LOAD_PCT,
    curr.AVG_CURRENT,
    CASE WHEN m.RATED_CURRENT > 0 AND curr.AVG_CURRENT IS NOT NULL
         THEN ROUND(curr.AVG_CURRENT / m.RATED_CURRENT * 100, 1) ELSE NULL END AS CURRENT_PCT,
    CASE WHEN COALESCE(ms.EVENT_TYPE,'') IN ('SHUTDOWN') OR m.OPERATING_STATE IN ('OFFLINE','MAINTENANCE')
         THEN TRUE ELSE FALSE END AS SUPPRESS_SIGNALS,
    ms.EVENT_TIMESTAMP AS LAST_STATE_CHANGE
FROM RAW.MACHINES m
LEFT JOIN machine_state ms ON m.MACHINE_ID = ms.MACHINE_ID
LEFT JOIN (
    SELECT MACHINE_ID, ROUND(AVG(READING_VALUE),2) AS AVG_RPM
    FROM RAW.SENSOR_READINGS WHERE SIGNAL_TYPE = 'RPM'
      AND READING_TIMESTAMP >= DATEADD('hour', -6, CURRENT_TIMESTAMP()) GROUP BY MACHINE_ID
) rpm ON m.MACHINE_ID = rpm.MACHINE_ID
LEFT JOIN (
    SELECT MACHINE_ID, ROUND(AVG(READING_VALUE),2) AS AVG_CURRENT
    FROM RAW.SENSOR_READINGS WHERE SIGNAL_TYPE = 'CURRENT'
      AND READING_TIMESTAMP >= DATEADD('hour', -6, CURRENT_TIMESTAMP()) GROUP BY MACHINE_ID
) curr ON m.MACHINE_ID = curr.MACHINE_ID;

-- ============================================================
-- DT3: STAGING.MACHINE_HEALTH_FEATURES
-- Hourly aggregates with rolling windows and trend features
-- ============================================================
CREATE OR REPLACE DYNAMIC TABLE STAGING.MACHINE_HEALTH_FEATURES
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = IOT_PM_WH
    AS
WITH hourly_stats AS (
    SELECT MACHINE_ID, SIGNAL_TYPE,
        DATE_TRUNC('hour', READING_TIMESTAMP) AS HOUR_BUCKET,
        ROUND(AVG(NORMALIZED_VALUE), 4) AS AVG_VALUE,
        ROUND(MAX(NORMALIZED_VALUE), 4) AS MAX_VALUE,
        ROUND(MIN(NORMALIZED_VALUE), 4) AS MIN_VALUE,
        ROUND(STDDEV(NORMALIZED_VALUE), 4) AS STD_VALUE,
        COUNT(*) AS READING_COUNT,
        SUM(CASE WHEN THRESHOLD_STATUS = 'WARNING' THEN 1 ELSE 0 END) AS WARNING_COUNT,
        SUM(CASE WHEN THRESHOLD_STATUS = 'CRITICAL' THEN 1 ELSE 0 END) AS CRITICAL_COUNT,
        SUM(CASE WHEN IS_SPIKE THEN 1 ELSE 0 END) AS SPIKE_COUNT,
        SUM(CASE WHEN QUALITY_FLAG != 'GOOD' THEN 1 ELSE 0 END) AS BAD_QUALITY_COUNT
    FROM STAGING.SENSOR_READINGS_CLEAN
    GROUP BY MACHINE_ID, SIGNAL_TYPE, DATE_TRUNC('hour', READING_TIMESTAMP)
)
SELECT h.*,
    ROUND(AVG(h.AVG_VALUE) OVER (PARTITION BY h.MACHINE_ID, h.SIGNAL_TYPE ORDER BY h.HOUR_BUCKET ROWS BETWEEN 5 PRECEDING AND CURRENT ROW), 4) AS ROLLING_6H_AVG,
    ROUND(AVG(h.AVG_VALUE) OVER (PARTITION BY h.MACHINE_ID, h.SIGNAL_TYPE ORDER BY h.HOUR_BUCKET ROWS BETWEEN 23 PRECEDING AND CURRENT ROW), 4) AS ROLLING_24H_AVG,
    ROUND(h.AVG_VALUE - LAG(h.AVG_VALUE, 6) OVER (PARTITION BY h.MACHINE_ID, h.SIGNAL_TYPE ORDER BY h.HOUR_BUCKET), 4) AS RATE_OF_CHANGE_6H,
    ROUND(h.AVG_VALUE - AVG(h.AVG_VALUE) OVER (PARTITION BY h.MACHINE_ID, h.SIGNAL_TYPE ORDER BY h.HOUR_BUCKET ROWS BETWEEN 167 PRECEDING AND CURRENT ROW), 4) AS BASELINE_DEVIATION_7D,
    ROUND(STDDEV(h.STD_VALUE) OVER (PARTITION BY h.MACHINE_ID, h.SIGNAL_TYPE ORDER BY h.HOUR_BUCKET ROWS BETWEEN 23 PRECEDING AND CURRENT ROW), 4) AS VARIABILITY_TREND_24H
FROM hourly_stats h;

-- ============================================================
-- DT4: STAGING.PERFORMANCE_BASELINE
-- Shift-over-shift and 7-day production baselines
-- ============================================================
CREATE OR REPLACE DYNAMIC TABLE STAGING.PERFORMANCE_BASELINE
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = IOT_PM_WH
    AS
SELECT
    pq.MACHINE_ID, pq.SHIFT, pq.PRODUCTION_DATE,
    pq.ACTUAL_UNITS, pq.GOOD_UNITS, pq.REJECTED_UNITS,
    pq.CYCLE_TIME_SEC, pq.IDEAL_CYCLE_TIME_SEC,
    pq.ACTUAL_RUNTIME_HRS, pq.DOWNTIME_HRS, pq.PRODUCTION_STATUS,
    LAG(pq.ACTUAL_UNITS, 1) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE) AS PREV_DAY_UNITS,
    ROUND(CASE WHEN LAG(pq.ACTUAL_UNITS, 1) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE) > 0 THEN
        (pq.ACTUAL_UNITS - LAG(pq.ACTUAL_UNITS, 1) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE))::FLOAT
        / LAG(pq.ACTUAL_UNITS, 1) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE) * 100
    ELSE NULL END, 2) AS SHIFT_OVER_SHIFT_PCT,
    ROUND(AVG(pq.ACTUAL_UNITS) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 1) AS ROLLING_7D_AVG_UNITS,
    ROUND(AVG(CASE WHEN pq.ACTUAL_UNITS > 0 THEN pq.REJECTED_UNITS::FLOAT / pq.ACTUAL_UNITS * 100 ELSE 0 END) OVER (
        PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS ROLLING_7D_REJECT_RATE,
    ROUND(CASE WHEN AVG(pq.ACTUAL_UNITS) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) > 0 THEN
        (pq.ACTUAL_UNITS - AVG(pq.ACTUAL_UNITS) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW))
        / AVG(pq.ACTUAL_UNITS) OVER (PARTITION BY pq.MACHINE_ID, pq.SHIFT ORDER BY pq.PRODUCTION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) * 100
    ELSE NULL END, 2) AS PERF_DEGRADATION_VS_7D
FROM RAW.PRODUCTION_QUALITY pq;

-- ============================================================
-- DT5: STAGING.CROSS_MACHINE_HEALTH
-- Fleet-wide health scoring and concern ranking
-- ============================================================
CREATE OR REPLACE DYNAMIC TABLE STAGING.CROSS_MACHINE_HEALTH
    TARGET_LAG = '5 minutes'
    WAREHOUSE = IOT_PM_WH
    AS
WITH latest_features AS (
    SELECT MACHINE_ID, SIGNAL_TYPE,
        MAX(HOUR_BUCKET) AS LATEST_HOUR,
        MAX_BY(AVG_VALUE, HOUR_BUCKET) AS LATEST_AVG,
        MAX_BY(ROLLING_24H_AVG, HOUR_BUCKET) AS LATEST_24H_AVG,
        MAX_BY(BASELINE_DEVIATION_7D, HOUR_BUCKET) AS LATEST_BASELINE_DEV,
        MAX_BY(RATE_OF_CHANGE_6H, HOUR_BUCKET) AS LATEST_ROC,
        SUM(WARNING_COUNT) AS TOTAL_WARNINGS_24H,
        SUM(CRITICAL_COUNT) AS TOTAL_CRITICALS_24H,
        SUM(SPIKE_COUNT) AS TOTAL_SPIKES_24H,
        SUM(BAD_QUALITY_COUNT) AS TOTAL_BAD_QUALITY_24H
    FROM STAGING.MACHINE_HEALTH_FEATURES
    WHERE HOUR_BUCKET >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
    GROUP BY MACHINE_ID, SIGNAL_TYPE
),
machine_signal_scores AS (
    SELECT MACHINE_ID, SIGNAL_TYPE,
        GREATEST(0, LEAST(100,
            100
            - (CASE WHEN TOTAL_CRITICALS_24H > 0 THEN 30 ELSE 0 END)
            - (CASE WHEN TOTAL_WARNINGS_24H > 3 THEN 20 WHEN TOTAL_WARNINGS_24H > 0 THEN 10 ELSE 0 END)
            - (CASE WHEN ABS(COALESCE(LATEST_BASELINE_DEV, 0)) > 3 THEN 15 ELSE 0 END)
            - (CASE WHEN TOTAL_SPIKES_24H > 5 THEN 10 WHEN TOTAL_SPIKES_24H > 0 THEN 5 ELSE 0 END)
            - (CASE WHEN TOTAL_BAD_QUALITY_24H > 5 THEN 10 ELSE 0 END)
            - (CASE WHEN ABS(COALESCE(LATEST_ROC, 0)) > 2 THEN 10 ELSE 0 END)
        )) AS SIGNAL_HEALTH_SCORE
    FROM latest_features
)
SELECT
    m.MACHINE_ID, m.MACHINE_NAME, m.MACHINE_TYPE, m.LINE, m.CRITICALITY,
    ctx.CURRENT_STATE, ctx.LOAD_PCT, ctx.SUPPRESS_SIGNALS,
    ROUND(AVG(mss.SIGNAL_HEALTH_SCORE), 1) AS HEALTH_SCORE,
    CASE WHEN AVG(mss.SIGNAL_HEALTH_SCORE) >= 80 THEN 'HEALTHY'
         WHEN AVG(mss.SIGNAL_HEALTH_SCORE) >= 60 THEN 'WARNING'
         WHEN AVG(mss.SIGNAL_HEALTH_SCORE) >= 40 THEN 'DEGRADED'
         ELSE 'CRITICAL' END AS HEALTH_STATUS,
    RANK() OVER (ORDER BY AVG(mss.SIGNAL_HEALTH_SCORE) ASC) AS CONCERN_RANK,
    SUM(CASE WHEN mss.SIGNAL_HEALTH_SCORE < 60 THEN 1 ELSE 0 END) AS SIGNALS_AT_RISK,
    MIN(mss.SIGNAL_HEALTH_SCORE) AS WORST_SIGNAL_SCORE,
    MIN_BY(mss.SIGNAL_TYPE, mss.SIGNAL_HEALTH_SCORE) AS WORST_SIGNAL_TYPE,
    CURRENT_TIMESTAMP() AS COMPUTED_AT
FROM RAW.MACHINES m
LEFT JOIN STAGING.MACHINE_OPERATING_CONTEXT ctx ON m.MACHINE_ID = ctx.MACHINE_ID
LEFT JOIN machine_signal_scores mss ON m.MACHINE_ID = mss.MACHINE_ID
GROUP BY m.MACHINE_ID, m.MACHINE_NAME, m.MACHINE_TYPE, m.LINE, m.CRITICALITY,
         ctx.CURRENT_STATE, ctx.LOAD_PCT, ctx.SUPPRESS_SIGNALS;

-- ============================================================
-- DT6: ANALYTICS.MAINTENANCE_CONTEXT
-- Enriched machine context with maintenance, operator, production, parts
-- ============================================================
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.MAINTENANCE_CONTEXT
    TARGET_LAG = '5 minutes'
    WAREHOUSE = IOT_PM_WH
    AS
SELECT
    cmh.MACHINE_ID, cmh.MACHINE_NAME, cmh.MACHINE_TYPE, cmh.LINE, cmh.CRITICALITY,
    cmh.CURRENT_STATE, cmh.HEALTH_SCORE, cmh.HEALTH_STATUS, cmh.CONCERN_RANK,
    cmh.WORST_SIGNAL_TYPE, cmh.WORST_SIGNAL_SCORE, cmh.SIGNALS_AT_RISK,
    mh.MAINTENANCE_ID AS LAST_MAINT_ID, mh.FAILURE_MODE AS LAST_FAILURE_MODE,
    mh.ROOT_CAUSE AS LAST_ROOT_CAUSE, mh.COMPLETED_AT AS LAST_MAINT_DATE,
    DATEDIFF('day', mh.COMPLETED_AT, CURRENT_TIMESTAMP()) AS DAYS_SINCE_LAST_MAINT,
    mh_count.FAILURE_COUNT, mh_count.TOTAL_MAINT_COST,
    sl.OBSERVATION_TYPE AS LATEST_OBS_TYPE, sl.OBSERVATION_DETAIL AS LATEST_OBS_DETAIL,
    sl.SEVERITY AS LATEST_OBS_SEVERITY, sl.OBSERVED_AT AS LATEST_OBS_TIME,
    pq.PRODUCTION_STATUS AS LATEST_PROD_STATUS, pq.ACTUAL_UNITS AS LATEST_ACTUAL_UNITS,
    pq.REJECTED_UNITS AS LATEST_REJECTED_UNITS,
    CASE WHEN pq.ACTUAL_UNITS > 0 THEN ROUND(pq.REJECTED_UNITS::FLOAT / pq.ACTUAL_UNITS * 100, 2) ELSE 0 END AS LATEST_REJECT_RATE,
    ev.RECENT_EVENT_COUNT, ev.RECENT_CRITICAL_EVENTS,
    parts.PARTS_AVAILABLE, parts.MIN_LEAD_TIME_DAYS,
    cmh.COMPUTED_AT
FROM STAGING.CROSS_MACHINE_HEALTH cmh
LEFT JOIN (SELECT *, ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY COMPLETED_AT DESC) AS rn FROM RAW.MAINTENANCE_HISTORY) mh ON cmh.MACHINE_ID = mh.MACHINE_ID AND mh.rn = 1
LEFT JOIN (SELECT MACHINE_ID, COUNT(*) AS FAILURE_COUNT, SUM(COST) AS TOTAL_MAINT_COST FROM RAW.MAINTENANCE_HISTORY GROUP BY MACHINE_ID) mh_count ON cmh.MACHINE_ID = mh_count.MACHINE_ID
LEFT JOIN (SELECT *, ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY OBSERVED_AT DESC) AS rn FROM RAW.SHIFT_LOGS) sl ON cmh.MACHINE_ID = sl.MACHINE_ID AND sl.rn = 1
LEFT JOIN (SELECT *, ROW_NUMBER() OVER (PARTITION BY MACHINE_ID ORDER BY PRODUCTION_DATE DESC, SHIFT DESC) AS rn FROM RAW.PRODUCTION_QUALITY) pq ON cmh.MACHINE_ID = pq.MACHINE_ID AND pq.rn = 1
LEFT JOIN (SELECT MACHINE_ID, COUNT(*) AS RECENT_EVENT_COUNT, SUM(CASE WHEN SEVERITY='CRITICAL' THEN 1 ELSE 0 END) AS RECENT_CRITICAL_EVENTS FROM RAW.MACHINE_EVENT_LOGS WHERE EVENT_TIMESTAMP >= DATEADD('day',-7,CURRENT_TIMESTAMP()) GROUP BY MACHINE_ID) ev ON cmh.MACHINE_ID = ev.MACHINE_ID
LEFT JOIN (SELECT m.MACHINE_ID, COUNT(DISTINCT p.PART_ID) AS PARTS_AVAILABLE, MIN(p.LEAD_TIME_DAYS) AS MIN_LEAD_TIME_DAYS FROM RAW.MACHINES m JOIN RAW.PARTS_INVENTORY p ON CONTAINS(p.COMPATIBLE_MACHINE_TYPES, m.MACHINE_TYPE) AND p.QUANTITY_ON_HAND > 0 GROUP BY m.MACHINE_ID) parts ON cmh.MACHINE_ID = parts.MACHINE_ID;
