-- ============================================================
-- 05_ml_pipeline.sql
-- Anomaly Detection, Failure Forecasts, Assessments, Incidents
-- Database: IOT_PREDICTIVE_MAINTENANCE | Warehouse: IOT_PM_WH
-- ============================================================

USE DATABASE IOT_PREDICTIVE_MAINTENANCE;
USE WAREHOUSE IOT_PM_WH;

-- ============================================================
-- ANALYTICS.DETECTED_ANOMALIES
-- Rule-based scoring from health features
-- ============================================================
CREATE OR REPLACE TABLE ANALYTICS.DETECTED_ANOMALIES AS
WITH anomaly_candidates AS (
    SELECT MACHINE_ID, SIGNAL_TYPE, HOUR_BUCKET AS DETECTION_TIMESTAMP,
        AVG_VALUE, ROLLING_24H_AVG, BASELINE_DEVIATION_7D, RATE_OF_CHANGE_6H,
        WARNING_COUNT, CRITICAL_COUNT, SPIKE_COUNT,
        GREATEST(0, LEAST(100,
            (CASE WHEN CRITICAL_COUNT > 0 THEN 40 ELSE 0 END) +
            (CASE WHEN WARNING_COUNT > 2 THEN 20 WHEN WARNING_COUNT > 0 THEN 10 ELSE 0 END) +
            (CASE WHEN ABS(COALESCE(BASELINE_DEVIATION_7D, 0)) > 5 THEN 20 WHEN ABS(COALESCE(BASELINE_DEVIATION_7D, 0)) > 3 THEN 10 ELSE 0 END) +
            (CASE WHEN ABS(COALESCE(RATE_OF_CHANGE_6H, 0)) > 3 THEN 15 WHEN ABS(COALESCE(RATE_OF_CHANGE_6H, 0)) > 1.5 THEN 8 ELSE 0 END) +
            (CASE WHEN SPIKE_COUNT > 3 THEN 10 WHEN SPIKE_COUNT > 0 THEN 5 ELSE 0 END)
        )) AS ANOMALY_SCORE
    FROM STAGING.MACHINE_HEALTH_FEATURES
    WHERE HOUR_BUCKET >= DATEADD('day', -7, CURRENT_TIMESTAMP())
)
SELECT
    ROW_NUMBER() OVER (ORDER BY DETECTION_TIMESTAMP, MACHINE_ID) AS ANOMALY_ID,
    MACHINE_ID, DETECTION_TIMESTAMP, SIGNAL_TYPE AS AFFECTED_SIGNAL, ANOMALY_SCORE,
    CASE WHEN ANOMALY_SCORE >= 60 THEN 'HIGH' WHEN ANOMALY_SCORE >= 35 THEN 'MEDIUM' WHEN ANOMALY_SCORE >= 15 THEN 'LOW' ELSE NULL END AS SEVERITY,
    AVG_VALUE AS SIGNAL_VALUE, ROLLING_24H_AVG, BASELINE_DEVIATION_7D, RATE_OF_CHANGE_6H,
    'STATISTICAL_RULE_V1' AS MODEL_ID,
    'Rule-based anomaly score from threshold breaches, baseline deviation, rate of change, and spike frequency' AS MODEL_DESCRIPTION,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM anomaly_candidates WHERE ANOMALY_SCORE >= 15;

-- ============================================================
-- ANALYTICS.FAILURE_FORECASTS
-- Trend-based failure prediction with RUL estimates
-- ============================================================
CREATE OR REPLACE TABLE ANALYTICS.FAILURE_FORECASTS AS
WITH daily_trends AS (
    SELECT MACHINE_ID, SIGNAL_TYPE,
        DATE_TRUNC('day', HOUR_BUCKET) AS DAY_BUCKET,
        ROUND(AVG(AVG_VALUE), 4) AS DAILY_AVG,
        ROUND(MAX(MAX_VALUE), 4) AS DAILY_MAX,
        SUM(WARNING_COUNT) AS DAILY_WARNINGS, SUM(CRITICAL_COUNT) AS DAILY_CRITICALS
    FROM STAGING.MACHINE_HEALTH_FEATURES
    GROUP BY MACHINE_ID, SIGNAL_TYPE, DATE_TRUNC('day', HOUR_BUCKET)
),
slope_calc AS (
    SELECT MACHINE_ID, SIGNAL_TYPE,
        MAX(DAY_BUCKET) AS LATEST_DAY,
        MAX_BY(DAILY_AVG, DAY_BUCKET) AS LATEST_AVG,
        MAX_BY(DAILY_MAX, DAY_BUCKET) AS LATEST_MAX,
        (AVG(CASE WHEN DAY_BUCKET >= DATEADD('day', -3, (SELECT MAX(DAY_BUCKET) FROM daily_trends)) THEN DAILY_AVG END)
         - AVG(CASE WHEN DAY_BUCKET BETWEEN DATEADD('day', -10, (SELECT MAX(DAY_BUCKET) FROM daily_trends))
                    AND DATEADD('day', -7, (SELECT MAX(DAY_BUCKET) FROM daily_trends)) THEN DAILY_AVG END)
        ) / NULLIF(7, 0) AS TREND_SLOPE_7D
    FROM daily_trends GROUP BY MACHINE_ID, SIGNAL_TYPE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY sc.MACHINE_ID, sc.SIGNAL_TYPE) AS FORECAST_ID,
    sc.MACHINE_ID, sc.SIGNAL_TYPE, sc.LATEST_DAY AS PREDICTION_DATE,
    CASE
        WHEN sc.SIGNAL_TYPE = 'VIBRATION' AND sc.TREND_SLOPE_7D > 0.2 THEN 'BEARING_DEGRADATION'
        WHEN sc.SIGNAL_TYPE = 'VIBRATION' AND sc.TREND_SLOPE_7D > 0.1 THEN 'MISALIGNMENT'
        WHEN sc.SIGNAL_TYPE = 'TEMPERATURE' AND sc.TREND_SLOPE_7D > 1.0 THEN 'OVERHEATING'
        WHEN sc.SIGNAL_TYPE = 'CURRENT' AND sc.TREND_SLOPE_7D > 0.5 THEN 'MOTOR_OVERLOAD'
        WHEN sc.SIGNAL_TYPE = 'PRESSURE' AND sc.TREND_SLOPE_7D < -1.0 THEN 'HYDRAULIC_SEAL_FAILURE'
        ELSE 'MONITORING'
    END AS PREDICTED_FAILURE_MODE,
    CASE
        WHEN s.CRITICAL_THRESHOLD IS NOT NULL AND sc.TREND_SLOPE_7D > 0
             AND (s.CRITICAL_THRESHOLD - sc.LATEST_AVG) / NULLIF(sc.TREND_SLOPE_7D, 0) <= 3 THEN '24_HOUR'
        WHEN s.CRITICAL_THRESHOLD IS NOT NULL AND sc.TREND_SLOPE_7D > 0
             AND (s.CRITICAL_THRESHOLD - sc.LATEST_AVG) / NULLIF(sc.TREND_SLOPE_7D, 0) <= 7 THEN '7_DAY'
        WHEN s.CRITICAL_THRESHOLD IS NOT NULL AND sc.TREND_SLOPE_7D > 0
             AND (s.CRITICAL_THRESHOLD - sc.LATEST_AVG) / NULLIF(sc.TREND_SLOPE_7D, 0) <= 30 THEN '30_DAY'
        WHEN sc.TREND_SLOPE_7D > 0 THEN 'BEYOND_30_DAY'
        ELSE 'STABLE'
    END AS RISK_HORIZON,
    CASE WHEN s.CRITICAL_THRESHOLD IS NOT NULL AND sc.TREND_SLOPE_7D > 0
        THEN ROUND((s.CRITICAL_THRESHOLD - sc.LATEST_AVG) / NULLIF(sc.TREND_SLOPE_7D, 0), 1) ELSE NULL
    END AS ESTIMATED_DAYS_TO_THRESHOLD,
    sc.LATEST_AVG AS CURRENT_VALUE, s.CRITICAL_THRESHOLD, ROUND(sc.TREND_SLOPE_7D, 4) AS TREND_SLOPE_7D,
    CASE
        WHEN ABS(COALESCE(sc.TREND_SLOPE_7D, 0)) > 0.3 AND sc.LATEST_MAX > COALESCE(s.WARNING_THRESHOLD, 99999) THEN 'HIGH'
        WHEN ABS(COALESCE(sc.TREND_SLOPE_7D, 0)) > 0.1 THEN 'MEDIUM'
        WHEN ABS(COALESCE(sc.TREND_SLOPE_7D, 0)) > 0.05 THEN 'LOW'
        ELSE 'INSUFFICIENT_DATA'
    END AS CONFIDENCE_LEVEL,
    'TREND_REGRESSION_V1' AS MODEL_VERSION,
    CURRENT_TIMESTAMP() AS PREDICTION_TIMESTAMP
FROM slope_calc sc
JOIN RAW.SENSORS s ON CONCAT(sc.MACHINE_ID, '-', sc.SIGNAL_TYPE) = s.SENSOR_ID;

-- ============================================================
-- ANALYTICS.FAILURE_ASSESSMENTS
-- Per-machine evidence aggregation and recommendations
-- ============================================================
CREATE OR REPLACE TABLE ANALYTICS.FAILURE_ASSESSMENTS AS
WITH machine_evidence AS (
    SELECT ff.MACHINE_ID, mc.MACHINE_NAME, mc.MACHINE_TYPE, mc.CRITICALITY,
        mc.HEALTH_SCORE, mc.HEALTH_STATUS,
        LISTAGG(DISTINCT CASE WHEN ff.PREDICTED_FAILURE_MODE != 'MONITORING' THEN ff.PREDICTED_FAILURE_MODE END, ', ') AS PREDICTED_MODES,
        MIN(CASE WHEN ff.PREDICTED_FAILURE_MODE != 'MONITORING' THEN ff.ESTIMATED_DAYS_TO_THRESHOLD END) AS MIN_DAYS_TO_THRESHOLD,
        MIN(CASE WHEN ff.PREDICTED_FAILURE_MODE != 'MONITORING' THEN ff.RISK_HORIZON END) AS WORST_RISK_HORIZON,
        MAX(CASE WHEN ff.PREDICTED_FAILURE_MODE != 'MONITORING' THEN ff.CONFIDENCE_LEVEL END) AS MAX_CONFIDENCE,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'VIBRATION' THEN ff.CURRENT_VALUE END) AS VIB_CURRENT,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'VIBRATION' THEN ff.TREND_SLOPE_7D END) AS VIB_SLOPE,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'TEMPERATURE' THEN ff.CURRENT_VALUE END) AS TEMP_CURRENT,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'TEMPERATURE' THEN ff.TREND_SLOPE_7D END) AS TEMP_SLOPE,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'CURRENT' THEN ff.CURRENT_VALUE END) AS CURR_CURRENT,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'CURRENT' THEN ff.TREND_SLOPE_7D END) AS CURR_SLOPE,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'PRESSURE' THEN ff.CURRENT_VALUE END) AS PRESS_CURRENT,
        MAX(CASE WHEN ff.SIGNAL_TYPE = 'PRESSURE' THEN ff.TREND_SLOPE_7D END) AS PRESS_SLOPE,
        mc.LAST_FAILURE_MODE, mc.LAST_ROOT_CAUSE, mc.DAYS_SINCE_LAST_MAINT, mc.FAILURE_COUNT,
        mc.LATEST_OBS_TYPE, mc.LATEST_OBS_DETAIL, mc.LATEST_OBS_SEVERITY,
        mc.LATEST_PROD_STATUS, mc.LATEST_REJECT_RATE
    FROM ANALYTICS.FAILURE_FORECASTS ff
    JOIN ANALYTICS.MAINTENANCE_CONTEXT mc ON ff.MACHINE_ID = mc.MACHINE_ID
    GROUP BY ff.MACHINE_ID, mc.MACHINE_NAME, mc.MACHINE_TYPE, mc.CRITICALITY,
             mc.HEALTH_SCORE, mc.HEALTH_STATUS, mc.LAST_FAILURE_MODE, mc.LAST_ROOT_CAUSE,
             mc.DAYS_SINCE_LAST_MAINT, mc.FAILURE_COUNT, mc.LATEST_OBS_TYPE, mc.LATEST_OBS_DETAIL,
             mc.LATEST_OBS_SEVERITY, mc.LATEST_PROD_STATUS, mc.LATEST_REJECT_RATE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY MIN_DAYS_TO_THRESHOLD NULLS LAST, HEALTH_SCORE) AS ASSESSMENT_ID,
    MACHINE_ID, MACHINE_NAME, MACHINE_TYPE, CRITICALITY, HEALTH_SCORE, HEALTH_STATUS,
    COALESCE(SPLIT_PART(PREDICTED_MODES, ',', 1), 'NONE_DETECTED') AS PRIMARY_FAILURE_MODE,
    PREDICTED_MODES AS ALL_PREDICTED_MODES,
    WORST_RISK_HORIZON AS RISK_HORIZON,
    MIN_DAYS_TO_THRESHOLD AS ESTIMATED_DAYS_TO_FAILURE,
    MAX_CONFIDENCE AS CONFIDENCE_LEVEL,
    OBJECT_CONSTRUCT(
        'vibration', OBJECT_CONSTRUCT('value', VIB_CURRENT, 'trend_per_day', VIB_SLOPE),
        'temperature', OBJECT_CONSTRUCT('value', TEMP_CURRENT, 'trend_per_day', TEMP_SLOPE),
        'current', OBJECT_CONSTRUCT('value', CURR_CURRENT, 'trend_per_day', CURR_SLOPE),
        'pressure', OBJECT_CONSTRUCT('value', PRESS_CURRENT, 'trend_per_day', PRESS_SLOPE),
        'maintenance_history', OBJECT_CONSTRUCT('last_failure_mode', LAST_FAILURE_MODE, 'last_root_cause', LAST_ROOT_CAUSE, 'days_since_last', DAYS_SINCE_LAST_MAINT, 'total_failures', FAILURE_COUNT),
        'operator_observation', OBJECT_CONSTRUCT('type', LATEST_OBS_TYPE, 'detail', LATEST_OBS_DETAIL, 'severity', LATEST_OBS_SEVERITY),
        'production', OBJECT_CONSTRUCT('status', LATEST_PROD_STATUS, 'reject_rate_pct', LATEST_REJECT_RATE)
    ) AS EVIDENCE_JSON,
    CONCAT(
        MACHINE_NAME, ' (', MACHINE_TYPE, ', ', CRITICALITY, ' criticality): ',
        CASE WHEN VIB_SLOPE > 0.1 THEN CONCAT('Vibration trending up at ', ROUND(VIB_SLOPE, 2), ' mm/s per day (current: ', ROUND(VIB_CURRENT, 1), ' mm/s). ') ELSE '' END,
        CASE WHEN TEMP_SLOPE > 0.5 THEN CONCAT('Temperature rising at ', ROUND(TEMP_SLOPE, 1), ' C/day (current: ', ROUND(TEMP_CURRENT, 1), ' C). ') ELSE '' END,
        CASE WHEN CURR_SLOPE > 0.3 THEN CONCAT('Current draw increasing at ', ROUND(CURR_SLOPE, 2), ' A/day. ') ELSE '' END,
        CASE WHEN PRESS_SLOPE < -1.0 THEN CONCAT('Pressure dropping at ', ROUND(ABS(PRESS_SLOPE), 1), ' bar/day. ') ELSE '' END,
        CASE WHEN LAST_FAILURE_MODE IS NOT NULL THEN CONCAT('Prior failure: ', LAST_FAILURE_MODE, '. ') ELSE '' END,
        CASE WHEN LATEST_OBS_SEVERITY IN ('MEDIUM','HIGH') THEN CONCAT('Operator reported: ', LATEST_OBS_DETAIL, '. ') ELSE '' END,
        CASE WHEN LATEST_PROD_STATUS = 'DEGRADED' THEN 'Production status: DEGRADED. ' ELSE '' END
    ) AS EVIDENCE_NARRATIVE,
    CASE
        WHEN MIN_DAYS_TO_THRESHOLD IS NOT NULL AND MIN_DAYS_TO_THRESHOLD <= 3 AND MAX_CONFIDENCE = 'HIGH' THEN 'IMMEDIATE_ACTION_REQUIRED'
        WHEN MIN_DAYS_TO_THRESHOLD IS NOT NULL AND MIN_DAYS_TO_THRESHOLD <= 7 THEN 'SCHEDULE_MAINTENANCE'
        WHEN PREDICTED_MODES IS NOT NULL AND PREDICTED_MODES != '' THEN 'MONITOR_CLOSELY'
        ELSE 'ROUTINE_MONITORING'
    END AS RECOMMENDATION,
    CASE
        WHEN MAX_CONFIDENCE = 'INSUFFICIENT_DATA' THEN 'MANUAL_INSPECTION_RECOMMENDED'
        WHEN HEALTH_SCORE IS NULL THEN 'MISSING_DATA'
        ELSE 'AUTOMATED_ASSESSMENT'
    END AS ASSESSMENT_STATE,
    CURRENT_TIMESTAMP() AS ASSESSED_AT
FROM machine_evidence;

-- ============================================================
-- ANALYTICS.INCIDENTS
-- Correlated incidents from failure assessments + anomalies
-- ============================================================
CREATE OR REPLACE TABLE ANALYTICS.INCIDENTS AS
WITH incident_source AS (
    SELECT fa.MACHINE_ID, fa.MACHINE_NAME, fa.MACHINE_TYPE, fa.CRITICALITY,
        fa.PRIMARY_FAILURE_MODE, fa.ALL_PREDICTED_MODES, fa.RISK_HORIZON,
        fa.ESTIMATED_DAYS_TO_FAILURE, fa.CONFIDENCE_LEVEL, fa.HEALTH_SCORE, fa.HEALTH_STATUS,
        fa.EVIDENCE_NARRATIVE, fa.EVIDENCE_JSON, fa.RECOMMENDATION, fa.ASSESSMENT_STATE,
        anom.ANOMALY_COUNT, anom.FIRST_ANOMALY_TIME, anom.LATEST_ANOMALY_TIME, anom.AFFECTED_SIGNALS,
        mc.LATEST_PROD_STATUS, mc.LATEST_REJECT_RATE, mc.LATEST_ACTUAL_UNITS,
        mc.PARTS_AVAILABLE, mc.MIN_LEAD_TIME_DAYS
    FROM ANALYTICS.FAILURE_ASSESSMENTS fa
    JOIN ANALYTICS.MAINTENANCE_CONTEXT mc ON fa.MACHINE_ID = mc.MACHINE_ID
    LEFT JOIN (
        SELECT MACHINE_ID, COUNT(*) AS ANOMALY_COUNT, MIN(DETECTION_TIMESTAMP) AS FIRST_ANOMALY_TIME,
            MAX(DETECTION_TIMESTAMP) AS LATEST_ANOMALY_TIME, LISTAGG(DISTINCT AFFECTED_SIGNAL, ', ') AS AFFECTED_SIGNALS
        FROM ANALYTICS.DETECTED_ANOMALIES WHERE SEVERITY IN ('HIGH','MEDIUM') AND DETECTION_TIMESTAMP >= DATEADD('day',-7,CURRENT_TIMESTAMP())
        GROUP BY MACHINE_ID
    ) anom ON fa.MACHINE_ID = anom.MACHINE_ID
    WHERE fa.RECOMMENDATION IN ('IMMEDIATE_ACTION_REQUIRED','SCHEDULE_MAINTENANCE','MONITOR_CLOSELY')
)
SELECT
    CONCAT('INC-', LPAD(ROW_NUMBER() OVER (ORDER BY
        CASE WHEN RECOMMENDATION='IMMEDIATE_ACTION_REQUIRED' THEN 1 WHEN RECOMMENDATION='SCHEDULE_MAINTENANCE' THEN 2 ELSE 3 END,
        ESTIMATED_DAYS_TO_FAILURE NULLS LAST), 3, '0')) AS INCIDENT_ID,
    MACHINE_ID, MACHINE_NAME, MACHINE_TYPE, CRITICALITY,
    FIRST_ANOMALY_TIME AS INCIDENT_START, LATEST_ANOMALY_TIME AS LATEST_ACTIVITY,
    DATEDIFF('hour', FIRST_ANOMALY_TIME, CURRENT_TIMESTAMP()) AS INCIDENT_AGE_HOURS,
    PRIMARY_FAILURE_MODE AS SUSPECTED_FAILURE_MODE, ALL_PREDICTED_MODES, AFFECTED_SIGNALS,
    ANOMALY_COUNT AS RELATED_ANOMALY_COUNT,
    CASE WHEN RECOMMENDATION='IMMEDIATE_ACTION_REQUIRED' THEN 'CRITICAL' WHEN RECOMMENDATION='SCHEDULE_MAINTENANCE' THEN 'HIGH' ELSE 'MEDIUM' END AS SEVERITY,
    HEALTH_SCORE, HEALTH_STATUS, RISK_HORIZON, ESTIMATED_DAYS_TO_FAILURE AS RUL_DAYS, CONFIDENCE_LEVEL,
    LATEST_PROD_STATUS AS PRODUCTION_IMPACT, LATEST_REJECT_RATE AS REJECT_RATE_PCT,
    EVIDENCE_NARRATIVE, EVIDENCE_JSON,
    GREATEST(0, LEAST(100,
        (100 - COALESCE(HEALTH_SCORE, 50)) * 0.3 +
        CASE WHEN CRITICALITY='HIGH' THEN 20 WHEN CRITICALITY='MEDIUM' THEN 10 ELSE 5 END +
        CASE WHEN LATEST_PROD_STATUS='DEGRADED' THEN 20 WHEN LATEST_REJECT_RATE > 5 THEN 15 WHEN LATEST_REJECT_RATE > 3 THEN 10 ELSE 0 END +
        CASE WHEN ESTIMATED_DAYS_TO_FAILURE IS NOT NULL AND ESTIMATED_DAYS_TO_FAILURE <= 1 THEN 20
             WHEN ESTIMATED_DAYS_TO_FAILURE IS NOT NULL AND ESTIMATED_DAYS_TO_FAILURE <= 3 THEN 15
             WHEN ESTIMATED_DAYS_TO_FAILURE IS NOT NULL AND ESTIMATED_DAYS_TO_FAILURE <= 7 THEN 10 ELSE 0 END +
        CASE WHEN CONFIDENCE_LEVEL='HIGH' THEN 10 WHEN CONFIDENCE_LEVEL='MEDIUM' THEN 5 ELSE 0 END
    )) AS PRIORITY_SCORE,
    'NEW' AS STATUS,
    NULL AS OWNER, NULL AS ACKNOWLEDGED_AT, NULL AS SNOOZE_REASON,
    NULL AS ESCALATION_STATUS, NULL AS RESOLUTION_REASON, NULL AS FALSE_POSITIVE_REASON,
    PARTS_AVAILABLE, MIN_LEAD_TIME_DAYS,
    CURRENT_TIMESTAMP() AS CREATED_AT, CURRENT_TIMESTAMP() AS UPDATED_AT
FROM incident_source;

-- Widen STATUS column for lifecycle states
ALTER TABLE ANALYTICS.INCIDENTS ALTER COLUMN STATUS SET DATA TYPE VARCHAR(30);
